name:
  "Test via conan + dynamic linker"
on:
  push
jobs:
  test:
    if: |
      !contains(github.event.head_commit.message, 'WIP')

    strategy:
      matrix:
        nim: ['version-1-6']

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: alaviss/setup-nim@master
        with:
          path: '../nim'
          version: ${{ matrix.nim }}
      - run: |
          pip install conan
          conan install . --build=missing
          nimble -y develop
          nim c -r \
            --passL:"@$(pwd)/conanbuildinfo.gcc" \
            --passC:"@$(pwd)/conanbuildinfo.gcc" \
            -d:libgit2LinkMode=dlink \
            -d:libssh2LinkMode=dlink \
            tests/test1.nim
